name: jourapothole
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2            
  flutter_screenutil: ^5.9.3 
  intl: any
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dots_indicator: ^4.0.1
  flutter_svg: ^2.0.17
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.5
  flutter_otp_text_field: ^1.5.1+1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.0.3
  path_provider: ^2.1.0
  path: ^1.8.3
  dio: ^5.8.0+1
  http_parser: ^4.1.2
  easy_image_viewer: ^1.5.1
  google_maps_flutter: ^2.12.1
  video_player: ^2.9.5

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svg/


